//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekat
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kasa> Kasas { get; set; }
        public virtual DbSet<Racun> Racuns { get; set; }
        public virtual DbSet<Zaposleni> Zaposlenis { get; set; }
        public virtual DbSet<Sala> Salas { get; set; }
        public virtual DbSet<Proizvod> Proizvods { get; set; }
        public virtual DbSet<Cenovnik> Cenovniks { get; set; }
        public virtual DbSet<Stavka> Stavkas { get; set; }
        public virtual DbSet<Gost> Gosts { get; set; }
        public virtual DbSet<Radi> Radis { get; set; }
    }
}
