//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Radi
    {
        public int KonobarSifzap { get; set; }
        public int SalaRedBrSale { get; set; }
    
        public virtual Sala Sala { get; set; }
        public virtual Konobar Konobar { get; set; }
    }
}
