//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stavka
    {
        public int Rbst { get; set; }
        public string Kol { get; set; }
        public string Iznos { get; set; }
        public int CenovnikCenap { get; set; }
        public int CenovnikProizvodKodpr { get; set; }
        public int RacunIdr { get; set; }
        public int RacunKasaIdk { get; set; }
        public int RacunZaposleniSifzap { get; set; }
    
        public virtual Cenovnik Cenovnik { get; set; }
        public virtual Racun Racun { get; set; }
    }
}
